### ISSUE TITLE
Add a tag for installation

### ISSUE THREAD

**Issue by skelouse** [seal/lava-go#1]
Steps:
- https://github.com/seal/lava-go
- click "tags"
- "releases"
- "Draft a new release"
- "choose a tag"
- v0.0.1
- publish release

After this your cli can be installed with a simple command 
```shell
go install github.com/seal/lava-go@latest

# and ran with
lava-go
```

**Comment by will-x86** [comment]
Thank you sir 
I just did it I believe

**Comment by skelouse** [comment]
Sweet, installation works.  Although sadly not working for me on Ubuntu :(
